version: '3'
services:
  db:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

  webtronics:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      args:
        PROJECT_ENV: production
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

volumes:
  db_data: